version: 2
jobs:
  build:
    docker:
      - image: shimberger/docker-ci-builder
    steps:
      - checkout
      - run: cd ui && npm install
      - run: go get -d ./...
      - run: ./scripts/release_snapshot.sh